name: children_book_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  font_awesome_flutter: ^10.6.0
  cloud_firestore: ^4.9.0
  firebase_core: ^2.30.0
  firebase_storage: ^11.5.0
  url_launcher: ^6.2.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  
